<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JobSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('jobs')->insert([
            ['name' => 'Software Engineer'],
            ['name' => 'Data Scientist'],
            ['name' => 'Psychologist'],
            ['name' => 'Marketing Specialist'],
            ['name' => 'Project Manager'],
            ['name' => 'Business Analyst'],
            ['name' => 'Product Manager'],
            ['name' => 'Financial Analyst'],
            ['name' => 'Consultant'],
            ['name' => 'Entrepreneur'],
            ['name' => 'Teacher'],
            ['name' => 'Lecturer'],
            ['name' => 'HR Specialist'],
            ['name' => 'Graphic Designer'],
            ['name' => 'UI/UX Designer'],
            ['name' => 'Web Developer'],
            ['name' => 'Mobile Developer'],
            ['name' => 'Network Engineer'],
            ['name' => 'System Analyst'],
            ['name' => 'Database Administrator'],
            ['name' => 'Content Writer'],
            ['name' => 'Copywriter'],
            ['name' => 'Public Relations'],
            ['name' => 'Event Organizer'],
            ['name' => 'Accountant'],
            ['name' => 'Auditor'],
            ['name' => 'Lawyer'],
            ['name' => 'Psychiatrist'],
            ['name' => 'Doctor'],
            ['name' => 'Nurse'],
            ['name' => 'Pharmacist'],
            ['name' => 'Architect'],
            ['name' => 'Civil Engineer'],
            ['name' => 'Mechanical Engineer'],
            ['name' => 'Electrical Engineer'],
            ['name' => 'Data Analyst'],
            ['name' => 'Data Engineer'],
            ['name' => 'Digital Marketer'],
            ['name' => 'SEO Specialist'],
            ['name' => 'Social Media Specialist'],
            ['name' => 'Customer Service'],
            ['name' => 'Sales Executive'],
            ['name' => 'Store Manager'],
            ['name' => 'Chef'],
            ['name' => 'Hotel Manager'],
            ['name' => 'Flight Attendant'],
            ['name' => 'Pilot'],
            ['name' => 'Translator'],
            ['name' => 'Interpreter'],
            ['name' => 'Animator'],
            ['name' => 'Video Editor'],
            ['name' => 'Photographer'],
            ['name' => 'Musician'],
            ['name' => 'Artist'],
            ['name' => 'Fashion Designer'],
            ['name' => 'Interior Designer'],
            ['name' => 'Logistics Specialist'],
            ['name' => 'Supply Chain Analyst'],
            ['name' => 'Researcher'],
            ['name' => 'Scientist'],
            ['name' => 'Biologist'],
            ['name' => 'Chemist'],
            ['name' => 'Physicist'],
            ['name' => 'Geologist'],
            ['name' => 'Statistician'],
            ['name' => 'Actuary'],
            ['name' => 'Economist'],
            ['name' => 'Librarian'],
            ['name' => 'Editor'],
            ['name' => 'Journalist'],
            ['name' => 'Reporter'],
            ['name' => 'Producer'],
            ['name' => 'Director'],
            ['name' => 'Screenwriter'],
            ['name' => 'Radio Broadcaster'],
            ['name' => 'TV Presenter'],
            ['name' => 'Athlete'],
            ['name' => 'Coach'],
            ['name' => 'Personal Trainer'],
            ['name' => 'Tour Guide'],
            ['name' => 'Travel Agent'],
            ['name' => 'Barista'],
            ['name' => 'Waiter'],
            ['name' => 'Security Guard'],
            ['name' => 'Firefighter'],
            ['name' => 'Police Officer'],
            ['name' => 'Soldier'],
            ['name' => 'Mechanic'],
            ['name' => 'Technician'],
            ['name' => 'Farmer'],
            ['name' => 'Fisherman'],
            ['name' => 'Carpenter'],
            ['name' => 'Plumber'],
            ['name' => 'Electrician'],
            ['name' => 'Driver'],
            ['name' => 'Courier'],
            ['name' => 'Cleaner'],
            ['name' => 'Babysitter'],
            ['name' => 'Caretaker'],
            ['name' => 'Volunteer'],
            ['name' => 'Writer'],
            ['name' => 'Engineer'],
        ]);
    }
}
