<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('questions')->insert([
            [
                'question_text' => 'Saya menikmati berada di pusat perhatian.',
                'mbti_type' => 'E',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.8,
            ],
            [
                'question_text' => 'Saya lebih suka fokus pada detail daripada gambaran besar.',
                'mbti_type' => 'S',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.7,
            ],
            [
                'question_text' => 'Saya membuat keputusan berdasarkan logika dan alasan.',
                'mbti_type' => 'T',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.9,
            ],
            [
                'question_text' => 'Saya suka memiliki rencana dan mengikutinya.',
                'mbti_type' => 'J',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.85,
            ],
            [
                'question_text' => 'Saya merasa berenergi ketika menghabiskan waktu sendirian.',
                'mbti_type' => 'I',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.75,
            ],
            [
                'question_text' => 'Saya menikmati mengeksplorasi ide-ide abstrak dan konsep.',
                'mbti_type' => 'N',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.8,
            ],
            [
                'question_text' => 'Saya membuat keputusan berdasarkan perasaan dan nilai-nilai saya.',
                'mbti_type' => 'F',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.7,
            ],
            [
                'question_text' => 'Saya lebih suka menjaga opsi tetap terbuka daripada mengikuti rencana.',
                'mbti_type' => 'P',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.6,
            ],
            [
                'question_text' => 'Saya suka berdiskusi dengan banyak orang.',
                'mbti_type' => 'E',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.8,
            ],
            [
                'question_text' => 'Saya lebih suka bekerja sendiri daripada dalam kelompok.',
                'mbti_type' => 'I',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.7,
            ],
            [
                'question_text' => 'Saya lebih suka fakta daripada teori.',
                'mbti_type' => 'S',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.7,
            ],
            [
                'question_text' => 'Saya sering membayangkan kemungkinan masa depan.',
                'mbti_type' => 'N',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.8,
            ],
            [
                'question_text' => 'Saya membuat keputusan berdasarkan perasaan.',
                'mbti_type' => 'F',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.7,
            ],
            [
                'question_text' => 'Saya lebih suka spontanitas daripada perencanaan.',
                'mbti_type' => 'P',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.6,
            ],
            [
                'question_text' => 'Saya suka membuat daftar tugas.',
                'mbti_type' => 'J',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.8,
            ],
            [
                'question_text' => 'Saya mudah beradaptasi dengan perubahan.',
                'mbti_type' => 'P',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.7,
            ],
            [
                'question_text' => 'Saya lebih suka mendengarkan daripada berbicara.',
                'mbti_type' => 'I',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.7,
            ],
            [
                'question_text' => 'Saya suka mencoba hal-hal baru.',
                'mbti_type' => 'N',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.8,
            ],
            [
                'question_text' => 'Saya lebih suka rutinitas yang teratur.',
                'mbti_type' => 'J',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.7,
            ],
            [
                'question_text' => 'Saya sering mengandalkan intuisi.',
                'mbti_type' => 'N',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.7,
            ],
            [
                'question_text' => 'Saya suka membantu orang lain.',
                'mbti_type' => 'F',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.8,
            ],
            [
                'question_text' => 'Saya lebih suka keputusan berdasarkan data.',
                'mbti_type' => 'T',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.8,
            ],
            [
                'question_text' => 'Saya suka menjadi pusat perhatian.',
                'mbti_type' => 'E',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.8,
            ],
            [
                'question_text' => 'Saya lebih suka bekerja dengan jadwal yang fleksibel.',
                'mbti_type' => 'P',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.7,
            ],
            [
                'question_text' => 'Saya suka menganalisis masalah secara logis.',
                'mbti_type' => 'T',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.8,
            ],
            [
                'question_text' => 'Saya lebih suka suasana yang tenang.',
                'mbti_type' => 'I',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.7,
            ],
            [
                'question_text' => 'Saya suka merencanakan masa depan.',
                'mbti_type' => 'J',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.8,
            ],
            [
                'question_text' => 'Saya lebih suka berbicara daripada mendengarkan.',
                'mbti_type' => 'E',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.7,
            ],
            [
                'question_text' => 'Saya suka mempelajari hal baru.',
                'mbti_type' => 'N',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.8,
            ],
            [
                'question_text' => 'Saya lebih suka keputusan cepat.',
                'mbti_type' => 'J',
                'option_1' => 1,
                'option_2' => 2,
                'option_3' => 3,
                'option_4' => 4,
                'option_5' => 5,
                'certainty_factor' => 0.7,
            ],
        ]); // Total 30 pertanyaan
    }
}
